NO_JOB_OFFERS_CV_ONLY = "there are no specific vacancies on the career page, only the ability to leave a CV"
NO_JOB_OFFERS = "there are no specific vacancies on the career page"
NOT_WORKING_SITE = "site is down"
JOBS_OFFERS_ARE_DEEPER = "job vacancies located deeper on the site"
JOBS_OFFERS_ARE_PRESENT = "job vacancies are present on the career page"
NO_CAREER_PAGE = ""

NOT_IT_JOBS_OFFERS_ARE_PRESENT = "not it related job vacancies are present on the career page"






full_hire = {
  "01com.com": JOBS_OFFERS_ARE_PRESENT,
  "100blackmen-atlanta.org": NOT_IT_JOBS_OFFERS_ARE_PRESENT,
  "100percentit.com": JOBS_OFFERS_ARE_PRESENT,
  "10gen.com": JOBS_OFFERS_ARE_DEEPER,
  "10zig.com": JOBS_OFFERS_ARE_PRESENT,
  "111harleystreet.com": NO_JOB_OFFERS,
  "113doctor.com": NOT_IT_JOBS_OFFERS_ARE_PRESENT,
  "1902.software": JOBS_OFFERS_ARE_PRESENT,
  "1abb.com": JOBS_OFFERS_ARE_DEEPER,
  "1prospect.com": JOBS_OFFERS_ARE_DEEPER,
  "1spatial.com": JOBS_OFFERS_ARE_PRESENT,
  "1stclassholidays.com": NOT_IT_JOBS_OFFERS_ARE_PRESENT,
  "1stobject.com": JOBS_OFFERS_ARE_PRESENT,
  "1stonlinesolutions.com": JOBS_OFFERS_ARE_PRESENT,
  "2-control.nl": JOBS_OFFERS_ARE_PRESENT,
  "21chotel.com": JOBS_OFFERS_ARE_DEEPER,
  "247international.net",
  "247tailorsteel.com",
  "24hourdata.com",
  "2600hz.com",
  "27global.com",
  "2dehands.be",
  "2g-eng.com",
  "2getthere.eu",
  "2hps.com",
  "2nd.md",
  "34bigthings.com",
  "aciano.net",
  "advanciatech.com",
  "agroengineers.com",
  "alicetechnologies.com",
  "anna.money",
  "aotco.com",
  "branchengineering.com",
  "bridgestar.org",
  "brinjac.com",
  "civilengineeringjobs.com",
  "ckcps.com",
  "cogentsystems.com",
  "creative.gs",
  "delimp.com",
  "demmachines.com",
  "dunhameng.com",
  "enhancesoft.com",
  "enterprise.plc.uk",
  "espplay.co.uk",
  "flinchbaugh.com",
  "futures-for-children.org",
  "geektastic.com",
  "gesher-jds.org",
  "get-express-vpn.com",
  "gmugeo.com",
  "goshopmatic.com",
  "guardiangroup.com",
  "hamiltoncollege.co.uk",
  "highlandequip.com",
  "instagram-together.com",
  "keillar.com",
  "kotem.com",
  "lafrancecorp.com",
  "launchpad-class.org",
  "leftronic.com",
  "ljbrecruit.com",
  "michaudcooley.com",
  "mobilecom.co.id",
  "mongoliatalentnetwork.com",
  "mvisionsolutions.com",
  "ncomva.com",
  "netcrm.com",
  "newperspectivestudio.co.za",
  "onpage.com",
  "pagination.com",
  "pfimarketintelligence.com",
  "pmfind.com",
  "primestaff.com",
  "psg-dallas.com",
  "qilinux.org",
  "qualityhydraulics.com",
  "quickpractice.com",
  "radar.io",
  "ranfac.com",
  "raylightgames.com",
  "rdi.co.uk",
  "scottrotaryseals.com",
  "sellware.com",
  "senitor.com",
  "senseair.se",
  "soundtechmedia.com",
  "technicalchange.com",
  "tendercare.co.uk",
  "thebluelinegroup.com",
  "tidalsoftware.com",
  "trafficgroup.com",
  "travii.com",
  "universal-balancing.com",
  "ushaprojects.com",
  "vordel.com",
  "whatsmypower.com",
  "wnic.com",
  "wrightps.com",
  "wwcannon.com",
  "abprecision.co.uk",
  "admsofttech.com",
  "agile-scrum.com",
  "alcon.com",
  "annashipman.co.uk",
  "apwa-mn.org",
  "associaflorida.com",
  "aviationsupport.com",
  "baeumer.com",
  "bancsource.net",
  "bkrsoftware.com",
  "bonsecours.com",
  "capital-engineering.com",
  "ccedtech.com",
  "cliftonemag.co.uk",
  "cobey.com",
  "davenport-co.com",
  "draimar.com",
  "dreiseitl.com",
  "drfico.com",
  "dusterhandle.com",
  "edmundoptics.com.tw",
  "eikoncg.com",
  "eramosa.com",
  "euriskomobility.com",
  "focusnordic.no",
  "get-chips.com",
  "heja.io",
  "horizoneducational.com",
  "hyquestsolutions.com",
  "igaa.in",
  "immersedgames.com",
  "ingenicomm.net",
  "jeremyperson.com",
  "kagira.com",
  "lcv.org.uk",
  "lemonade.be",
  "maankadevelopers.com",
  "macai.net",
  "manhattan-exchange.com",
  "nasaratech.com",
  "nexon-engineering.de",
  "nhbsgroup.com",
  "pacificplayinc.com",
  "paper-coffee.de",
  "paulgregorymedia.com",
  "peccomponents.com",
  "preempt.com",
  "pulsetechnologies.com",
  "qsgsoft.com",
  "rdsi.com",
  "scada.co.id",
  "sharepointinterface.com",
  "shockcraft.co.nz",
  "soundsleephealth.com",
  "takenaka.eu",
  "thomsonreutersonvio.com",
  "toolstage.de",
  "tudawe.com",
  "urangatang.com",
  "wabccountry.com",
  "welchfluorocarbon.com",
  "wwf.org.uk",
  "zdnetcooljobs.com",
  "zlbusa.com",
  "advanceddataspectrum.co.uk",
  "albanycubscouts.org",
  "americas-society.org",
  "anexiagroup.com",
  "armyfuturewarrior.com",
  "avetta.com",
  "bsp-consulting.co.uk",
  "checkfront.com",
  "chiyodaphil.com.ph",
  "dusenbery.com",
  "edwardsengineering.co.uk",
  "erecruit.com",
  "expandresearch.com",
  "fda-zai-inc.com",
  "fordharrison.com",
  "funtownrvwaco.com",
  "glanbianutritionals.com",
  "hakimisolutions.com",
  "hansgrohe-middleeast.com",
  "headstartglobal.in",
  "hlhltd.co.uk",
  "hunted.com",
  "iamgroup.com.my",
  "icomplaints.in",
  "inaxtech.com",
  "indian-seo-company.com",
  "jobsatgulf.org",
  "johnjonelis.com",
  "kameleoon.com",
  "kickstarter.com",
  "knowarth.com",
  "luvmyorthodontist.com",
  "natixis-republiquetcheque.com",
  "pensionprotectionfund.org.uk",
  "pssportsquoteaccident.com",
  "pssportsquotephysio.com",
  "qagoma.qld.gov.au",
  "radio-days.co.uk",
  "riverstone.com.my",
  "sadaf-mit.com",
  "saltechsystems.com",
  "samproperty.com",
  "securahosting.com",
  "spareroom.mobi",
  "termanorthamerica.com",
  "tinytailstoyou.com",
  "udayton.edu",
  "vygon.co.uk",
  "wgengineering.com",
  "whoneedsengineers.com",
  "zparcheng.com",
  "dataplus-research.com",
  "neoito.com"
}



print(len(full_hire))