all_sites_list = [
    'ravebizz.com',
    'kv-gmbh.de',
    'realdolmen.com',
    'nrf.com',
    'helenzys.com',
    'kogneta.com',
    'assimilatetechnologies.com',
    'crisp.chat',
    # 'careers.codeandpepper.com',
    'hypepotamus.com',
    'codeandtrust.com',
    'advaris.com',
    'alithya.com/en',
    'visily.ai',
    'ccim.com',
    'sparshcommunications.com',
    'seraphinfotech.com',
    'ntegrity.com.au',
    'agencyvista.com',
    'choruscall.com',
    'real11.com',
    'singular.uk',
    'hestabit.com',
    'jobs.universalparks.com',
    'www.k12.wa.us',
    'clevercoding.com',
    'allpay.net',
    'greenlite.com.ng/home',
    'allpay.net',
    'volt.io',
    'magna.com',
    'boschrexroth.com',
    'ideastoimpacts.com',
    'chamberlain.edu',
    'xiengineering.com',
    'neo4j.com',
    'northboundpublishing.com',
    'thesiliconpartners.com',
    'mips.com',
    'futuresoftindia.com',
    'amazon.fr',
    'ivrcl.com',
    'futureplc.com',
                  ]

all_sites_list_part_two = [
    # 'refinitiv.com',
    'newperspectivestudio.co.za',
    'rycomarketing.ie',
    'reachuae.com',
    'ipaydna.biz',
    'cloudnetindia.com',
    'gong.com'
]